#!/bin/bash

# 下载并执行远程脚本
expect -c '
spawn bash <(curl -fsSLk https://raw.githubusercontent.com/bulianglin/demo/main/xrayL.sh) socks
expect "Please enter the code:"
send "33546\r"
expect "Please enter the second code:"
send "kkzhao2s\r"
expect "Please enter the third code:"
send "kdhfysf\r"
interact
'
